### ISSUE TITLE
Panic when closing

### ISSUE THREAD

**Issue by zegervdv** [mattn/efm-langserver#110]
I'm not sure if this is a neovim or efm issue, but when I close neovim with an efm-langserver attached to it I get the following message: `Client 1 quit with exit code 2 and signal 0`.

In the lsp logging I find these message everytime I close:
```
[ ERROR ] 2021-04-09T08:52:48+0200 ] ...e/tools/nvim/head/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"efm-langserver"	"stderr"	"2021/04/09 08:52:48 jsonrpc2 handler: sending response 3: jsonrpc2: connection is closed\n2021/04/09 08:52:48 efm-langserver: connections closed\n"
[ ERROR ] 2021-04-09T08:52:48+0200 ] ...e/tools/nvim/head/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"efm-langserver"	"stderr"	"panic: send on closed channel\n\n"
[ ERROR ] 2021-04-09T08:52:48+0200 ] ...e/tools/nvim/head/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"efm-langserver"	"stderr"	"goroutine 33 [running]:\ngithub.com/mattn/efm-langserver/langserver.(*langHandler).lintRequest.func1()\n\tgithub.com/mattn/efm-langserver/langserver/handler.go:202 +0x5d\ncreated by time.goFunc\n\ttime/sleep.go:180 +0x45\n"
```

Is this an efm issue? (I don't know much about go).

**Comment by zegervdv** [comment]
hm, this seems to have introduced a new issue:

```
[ ERROR ] 2021-04-09T10:35:42+0200 ] ...e/tools/nvim/head/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"efm-langserver"	"stderr"	"panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x55f2ca]\n\ngoroutine 19 [running]:\n"
[ ERROR ] 2021-04-09T10:35:42+0200 ] ...e/tools/nvim/head/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"efm-langserver"	"stderr"	"time.(*Timer).Stop(...)\n\ttime/sleep.go:78\ngithub.com/mattn/efm-langserver/langserver.(*langHandler).handleShutdown(0xc0001ee160, 0x5efcd0, 0xc000196000, 0xc0001e2120, 0xc0001800a0, 0x58ff60, 0xc00018d1e0, 0xc0001f7d60, 0x5455d4)\n\tgithub.com/mattn/efm-langserver/langserver/handle_shutdown.go:10 +0x2a\ngithub.com/mattn/efm-langserver/langserver.(*langHandler).handle(0xc0001ee160, 0x5efcd0, 0xc000196000, 0xc0001e2120, 0xc0001800a0, 0x0, 0x0, 0x0, 0x0)\n\tgithub.com/mattn/efm-langserver/langserver/handler.go:559 +0x19c\ngithub.com/sourcegraph/jsonrpc2.(*HandlerWithErrorConfigurer).Handle(0xc00018c770, 0x5efcd0, 0xc000196000, 0xc0001e2120, 0xc0001800a0)\n\tgithub.com/sourcegraph/jsonrpc2@v0.0.0-20191222043438-96c4efab7ee2/handler_with_error.go:21 +0x72\ngithub.com/sourcegraph/jsonrpc2.(*Conn).readMessages(0xc0001e2120, 0x5efcd0, 0xc000196000)\n\tgithub.com/sourcegraph/jsonrpc2@v0.0.0-20191222043438-96c4efab7ee2/jsonrpc2.go:522 +0x57e\ncreated by github.com/sourcegraph/jsonrpc2.NewConn\n\tgithub.com/sourcegraph/jsonrpc2@v0.0.0-20191222043438-96c4efab7ee2/jsonrpc2.go:334 +0x1d5\n"
```

**Comment by lucax88x** [comment]
Ah, so I'm not the only one, I'm having this error and eslint suddenly stop working, is this the cause?

**Comment by zegervdv** [comment]
Probably.
@mattn can you reopen this issue or do I need to create a new one?

**Comment by Gelio** [comment]
I've also noticed the `panic` problem and created https://github.com/mattn/efm-langserver/pull/113 to hopefully fix it 🙂

**Comment by lucax88x** [comment]
Do @mattn  need to create a new release in order to download a new version and test it?

**Comment by Gelio** [comment]
@lucax88x I believe you can upgrade the version you have locally with

```sh
go get -u github.com/mattn/efm-langserver
```

**Comment by Gelio** [comment]
On my other PC the `go get -u` command did not upgrade the binary and the problem was not solved. What helped in this case was:

```sh
go get github.com/mattn/efm-langserver@master
```
