### ISSUE TITLE
panic:  invalid memory address or nil pointer dereference when linting svelte files

### ISSUE THREAD

**Issue by davidkariuki** [mattn/efm-langserver#117]
FWIW it works fine with other file types.

```bash
[ ERROR ] 2021-04-23T10:48:02+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]   "rpc"   "/home/me/.local/share/nvim/lspinstall/efm/./efm-langserver"     "stderr"        "2021/04/23 10:48:02 eslint_d --fix-to-stdout --stdin --stdin-filename=/home/me/projects/svelte-course/src/App.svelte: \n"
[ ERROR ] 2021-04-23T10:48:02+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]   "rpc"   "/home/me/.local/share/nvim/lspinstall/efm/./efm-langserver"     "stderr"        "panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x56df26]\n\ngoroutine 18 [running]:\ngithub.com/mattn/efm-langserver/langserver.(*langHandler).linter.func1(0xc0000b4000, 0x5efcd8, 0xc000104000, 0xc000022c80, 0x35)\n\t/home/me/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/mattn/efm-langserver@v0.0.29/langserver/handler.go:250 +0x1c6\ncreated by github.com/mattn/efm-langserver/langserver.(*langHandler).linter\n\t/home/me/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/mattn/efm-langserver@v0.0.29/langserver/handler.go:233 +0xde\n"

```

**Comment by mattn** [comment]
Closing as stale: this was reported against a 2021 build and the code involved has changed substantially since (including several panic fixes, most recently in #298). The truncated stack trace isn't enough to pinpoint the original cause. Please reopen with a full trace if it still happens on a current release.

**Comment by mattn** [comment]
Sorry for the very late response. Closing this as it is old and can no longer be reproduced. If you still hit the same problem on a current release, please open a new issue.
