### ISSUE TITLE
panic: runtime error: slice bounds out of range [:-1]

### ISSUE THREAD

**Issue by fsouza** [mattn/efm-langserver#57]
Hi there, thank you very much for this cool project!

I noticed with a certain config, the server panics when starting up efm for Python files. In my local tests, it only happens if I try to use this script as a lint-command: https://github.com/fsouza/vimfiles/blob/main/langservers/bin/blackd-format

Here's the stacktrace:

```
panic: runtime error: slice bounds out of range [:-1]

goroutine 18 [running]:
github.com/mattn/efm-langserver/langserver.(*file).wordat(0xc0001119e0, 0x13, 0x4f, 0x0, 0x1)
        /users/fsouza/.go/pkg/mod/github.com/mattn/efm-langserver@v0.0.16-0.20200706142454-0b64dd8f71a6/langserver/handler.go:134 +0x2ed
github.com/mattn/efm-langserver/langserver.(*langhandler).lint(0xc000160120, 0xc000114b00, 0x34, 0x0, 0x0, 0x0, 0x0, 0x0)
        /users/fsouza/.go/pkg/mod/github.com/mattn/efm-langserver@v0.0.16-0.20200706142454-0b64dd8f71a6/langserver/handler.go:340 +0xc55
github.com/mattn/efm-langserver/langserver.(*langhandler).linter(0xc000160120)
        /users/fsouza/.go/pkg/mod/github.com/mattn/efm-langserver@v0.0.16-0.20200706142454-0b64dd8f71a6/langserver/handler.go:191 +0x9c
created by github.com/mattn/efm-langserver/langserver.newhandler
        /users/fsouza/.go/pkg/mod/github.com/mattn/efm-langserver@v0.0.16-0.20200706142454-0b64dd8f71a6/langserver/handler.go:82 +0x13f
```

I can try to create a small reproducer if this helps, but I was wondering if we should simply return an empty string in that handler when currPos doesn't change in the loop? Something like:

```diff
diff --git a/langserver/handler.go b/langserver/handler.go
index 6869872..4d2f159 100644
--- a/langserver/handler.go
+++ b/langserver/handler.go
@@ -131,6 +131,9 @@ func (f *File) WordAt(pos Position) string {
                }
                prevCls = currCls
        }
+       if currPos < 0 {
+               return ""
+       }
        return string(utf16.Decode(chars[prevPos:currPos]))
 }
```

**Comment by aktau** [comment]
I've seen the same, on shell files (shellcheck):

```
panic: runtime error: slice bounds out of range [:-1]

goroutine 6 [running]:
github.com/mattn/efm-langserver/langserver.(*File).WordAt(0xc0000616e0, 0x1f, 0x9, 0xc0000aa474, 0x1)
  /home/aktau/go/src/github.com/mattn/efm-langserver/langserver/handler.go:134 +0x2d1
github.com/mattn/efm-langserver/langserver.(*langHandler).lint(0xc000122120, 0xc0000148a0, 0x30, 0x0, 0x0, 0x0, 0x0, 0x0
  /home/aktau/go/src/github.com/mattn/efm-langserver/langserver/handler.go:340 +0xc23
github.com/mattn/efm-langserver/langserver (*langHandler).linter(0xc000122120)
  /home/aktau/go/src/github.com/mattn/efm-langserver/langserver/handler.go:191 +0x9c
created by github.com/mattn/efm-langserver/langserver.NewHandler\n\t/home/nicolashillegeer/go/src/github.com/mattn/efm-langserver/langserver/handler.go:82 +0x13f
```

**Comment by mattn** [comment]
Thanks. I'll look into it tonight.
