### ISSUE TITLE
Disable Linting for language

### ISSUE THREAD

**Issue by cloggier** [mattn/efm-langserver#87]
I have set up formatting for specific language (linting is done by separate LSP) and I am getting constant messages: `lint for LanguageID not supported: <lang>` logged. Is there a way to disable linting part and only keep `format*` configuration working for that language?

**Comment by mattn** [comment]
I don't understand why the logging message is treated as error.

**Comment by cloggier** [comment]
It's not. It just pollutes logs a lot.

**Comment by dklymenk** [comment]
Not sure if I should create a separate issue or is my current issue related to this one.

I want to use prettier with [twig](https://twig.symfony.com/) via efm. I have prettier and the necessary extension for twig installed globally. Prettier works fine via both cli and efm. Here are some relevant lua configs:
```lua
...
local prettier_twig = {formatCommand = "prettier --tab-width 4 --stdin-filepath ${INPUT}", formatStdin = true}

require"lspconfig".efm.setup {
    cmd = {DATA_PATH .. "/lspinstall/efm/efm-langserver"},
    init_options = {documentFormatting = true, codeAction = false},
    filetypes = {"lua", "python", "javascriptreact", "javascript", "typescript","typescriptreact","sh", "html", "css", "json", "yaml", "markdown", "vue", "twig"},
    root_dir = require('lspconfig/util').root_pattern("node_modules", "tsconfig.json", "jsconfig.json", ".git"),
    settings = {
        languages = {
            ...
            twig = {prettier_twig}
        }
    }
}
```

So formatting works, but every time I exit vim I see "Client 1 quit with exit code 2 and signal 0" error. Relevant logs from `~/.cache/nvim/lsp.log`:

```
[ START ] 2021-05-11T14:36:29+0300 ] LSP logging initiated
[ ERROR ] 2021-05-11T14:36:30+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]  "rpc"   "/home/dklymenk/.local/share/nvim/lspinstall/efm/efm-langserver"       "stderr"        "2021/05/11 14:36:30 efm-langserver: no configuration file\n2021/05/11 14:36:30 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-05-11T14:36:31+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]  "rpc"   "/home/dklymenk/.local/share/nvim/lspinstall/efm/efm-langserver"       "stderr"        "2021/05/11 14:36:31 lint for LanguageID not supported: twig\n"
[ ERROR ] 2021-05-11T14:36:32+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]  "rpc"   "/home/dklymenk/.local/share/nvim/lspinstall/efm/efm-langserver"       "stderr"        "panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x55f2ca]\n\ngoroutine 7 [running]:\n"
[ ERROR ] 2021-05-11T14:36:32+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]  "rpc"   "/home/dklymenk/.local/share/nvim/lspinstall/efm/efm-langserver"       "stderr"        "time.(*Timer).Stop(...)\n\t/usr/lib/go/src/time/sleep.go:78\ngithub.com/mattn/efm-langserver/langserver.(*langHandler).handleShutdown(0xc00012e000, 0x5efd10, 0xc000014110, 0xc000132000, 0xc0000663c0, 0x58ff60, 0xc000011010, 0xc000125d60, 0x5455d4)\n\t/home/dklymenk/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/mattn/efm-langserver@v0.0.29/langserver/handle_shutdown.go:10 +0x2a\ngithub.com/mattn/efm-langserver/langserver.(*langHandler).handle(0xc00012e000, 0x5efd10, 0xc000014110, 0xc000132000, 0xc0000663c0, 0x0, 0x0, 0x0, 0x0)\n\t/home/dklymenk/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/mattn/efm-langserver@v0.0.29/langserver/handler.go:559 +0x19c\ngithub.com/sourcegraph/jsonrpc2.(*HandlerWithErrorConfigurer).Handle(0xc0000104d0, 0x5efd10, 0xc000014110, 0xc000132000, 0xc0000663c0)\n\t/home/dklymenk/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.0.0-20191222043438-96c4efab7ee2/handler_with_error.go:21 +0x72\ngithub.com/sourcegraph/jsonrpc2.(*Conn).readMessages(0xc000132000, 0x5efd10, 0xc000014110)\n\t/home/dklymenk/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.0.0-20191222043438-96c4efab7ee2/jsonrpc2.go:522 +0x57e\ncreated by github.com/sourcegraph/jsonrpc2.NewConn\n\t/home/dklymenk/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.0.0-20191222043438-96c4efab7ee2/jsonrpc2.go:334 +0x1d5\n"
```

One of the errors is `2021/05/11 14:36:31 lint for LanguageID not supported: twig\n`, but I'm not exactly sure if disabling linting would resolve other errors.

Actually, while formatting works flawlessly, it also produces a bunch of "error" logs in `~/.cache/nvim/lsp.log`. Stuff like `no configuration file` and `invalid memory address or nil pointer deference` is present there as well, but I honestly don't care about how clean those logs are, I kinda only care about the `Client 1 quit with exit code 2 and signal 0` error when I close vim.

Please, let me know If I should create a separate issue. Thanks.

**Comment by mattn** [comment]
How about to change the log-level?

```diff
diff --git a/langserver/handler.go b/langserver/handler.go
index 510f300..9bd41f0 100644
--- a/langserver/handler.go
+++ b/langserver/handler.go
@@ -354,7 +354,9 @@ func (h *langHandler) lint(ctx context.Context, uri DocumentURI) ([]Diagnostic,
 	}
 
 	if len(configs) == 0 {
-		h.logger.Printf("lint for LanguageID not supported: %v", f.LanguageID)
+		if h.loglevel >= 1 {
+			h.logger.Printf("lint for LanguageID not supported: %v", f.LanguageID)
+		}
 		return []Diagnostic{}, nil
 	}
 
```

**Comment by cloggier** [comment]
Ah, perfect. That makes sense. Good to know about it if one is debugging. Not very useful otherwise. 

Thanks!
